name: CI

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      CANVAS_API_ROOT: "https://canvas.its.virginia.edu/api/v1"
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN_CI }}  # noqa
      PYTEST_VALID_COURSE_ID: "126335"
      VCR_CASSETTE_DIR: "tests/cassettes"
      PYTHONWARNINGS: "ignore::DeprecationWarning" # Suppress VCR.py deprecation warnings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run linters and type checker
        run: uv run pre-commit run --all-files

      - name: Run Pytest with Coverage
        env:
          CANVAS_API_ROOT: "https://canvas.its.virginia.edu/api/v1"
          PYTEST_VALID_COURSE_ID: "126335"
          VCR_CASSETTE_DIR: "tests/cassettes/"
        run: uv run pytest --cov=src/canvas_gci --cov-report=term-missing --cov-fail-under=90 tests/
